import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Parameters for the problem
a = 3  # Radius of sphere
b = 2  # Radius of cylinder (must be less than a)

# Create a grid for visualization
theta = np.linspace(0, 2*np.pi, 100)
r = np.linspace(0, b, 50)  # Only go up to radius b as per constraint
theta_grid, r_grid = np.meshgrid(theta, r)

# Convert to cartesian coordinates
x = r_grid * np.cos(theta_grid)
y = r_grid * np.sin(theta_grid)

# Calculate z from the sphere equation x^2 + y^2 + z^2 = a^2
# We only want the positive z (above the xy-plane)
z = np.sqrt(a**2 - x**2 - y**2)

# Create the figure and a 3D axis
fig = plt.figure(figsize=(12, 10))
ax = fig.add_subplot(111, projection='3d')

# Plot the portion of the sphere above the xy-plane and within the cylinder
surf = ax.plot_surface(x, y, z, alpha=0.7, color='skyblue', edgecolor='none')

# Plot the bounding cylinder
cylinder_height = np.max(z) + 0.5
phi = np.linspace(0, 2*np.pi, 100)
z_cylinder = np.linspace(0, cylinder_height, 50)
phi_grid, z_grid = np.meshgrid(phi, z_cylinder)
x_cylinder = b * np.cos(phi_grid)
y_cylinder = b * np.sin(phi_grid)
ax.plot_surface(x_cylinder, y_cylinder, z_grid, alpha=0.2, color='green')

# Plot the base circle (intersection of cylinder with xy-plane)
base_x = b * np.cos(theta)
base_y = b * np.sin(theta)
base_z = np.zeros_like(theta)
ax.plot(base_x, base_y, base_z, color='red', linewidth=3)

# Set title and axis labels
ax.set_title(f'Area of portion of sphere $x^2 + y^2 + z^2 = {a}^2$ \nabove xy-plane and within cylinder $x^2 + y^2 = {b}^2$')
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')

# Set equal aspect ratio
max_range = np.array([x.max()-x.min(), y.max()-y.min(), z.max()-z.min()]).max() / 2.0
mid_x = (x.max()+x.min()) * 0.5
mid_y = (y.max()+y.min()) * 0.5
mid_z = (z.max()+z.min()) * 0.5
ax.set_xlim(mid_x - max_range, mid_x + max_range)
ax.set_ylim(mid_y - max_range, mid_y + max_range)
ax.set_zlim(0, mid_z + max_range)

# Add a note showing the mathematical formula for the area
formula = r"Area = $2\pi a (a - \sqrt{a^2 - b^2})$"
ax.text2D(0.05, 0.05, formula, transform=ax.transAxes, fontsize=12)

plt.show()

# Generated by Copilot
