# Generated by Copilot
import csv
import matplotlib.pyplot as plt

input_file = 'mom_with_stress_strain_excel.csv'
output_plot = 'stress_strain_curve_with_modulus.png'

# Read the data
stress = []
strain = []
with open(input_file, newline='') as csvfile:
    reader = csv.reader(csvfile)
    next(reader)  # skip header
    for row in reader:
        try:
            s = float(row[2])
            e = float(row[3])
            stress.append(s)
            strain.append(e)
        except Exception:
            pass

# Select two points from the elastic zone (first two points)
x1, x2 = strain[0], strain[1]
y1, y2 = stress[0], stress[1]

# Calculate modulus of elasticity (slope)
modulus = (y2 - y1) / (x2 - x1)

# Plot stress-strain curve
plt.figure(figsize=(8,6))
plt.plot(strain, stress, marker='o', label='Stress-Strain Curve')
plt.scatter([x1, x2], [y1, y2], color='red', zorder=5, label='Elastic Points')
plt.plot([x1, x2], [y1, y2], color='green', linestyle='--', label='Elastic Slope')

# Annotate points
plt.annotate(f'({x1:.6f}, {y1:.2f})', (x1, y1), textcoords="offset points", xytext=(-30,10), ha='center', color='red')
plt.annotate(f'({x2:.6f}, {y2:.2f})', (x2, y2), textcoords="offset points", xytext=(30,-10), ha='center', color='red')

# Annotate modulus
plt.text(0.002, max(stress)*0.8, f'Modulus of Elasticity = {modulus:.2e} MPa', fontsize=12, color='green', bbox=dict(facecolor='white', alpha=0.7))

plt.xlabel('Strain')
plt.ylabel('Stress (MPa)')
plt.title('Stress-Strain Curve with Modulus of Elasticity')
plt.legend()
plt.grid(True)
plt.savefig(output_plot)
plt.close()
